// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbjywxtajiihsoddteod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ianl3eHRhamlpaHNvZGR0ZW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDAzMzIsImV4cCI6MjA2NzU3NjMzMn0.9ptL5EbKf5jIIEPxz4N7GKcT9EPycE5IlHDhYlYoMR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});